/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * popUp.java
 *
 * Created on 29-Oct-2013, 22:25:00
 */
package pipesrus;

/**
 *
 * @author root
 */
public class popUp extends javax.swing.JFrame {

    /** Creates new form popUp */
    public popUp() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pipeQuantityLabel = new javax.swing.JLabel();
        pipeQuantitySpinner = new javax.swing.JSpinner();
        pipeReinforcementCheckBox = new javax.swing.JCheckBox();
        pipeChemResCheckBox = new javax.swing.JCheckBox();
        pipeSizeDiameterTextField = new javax.swing.JTextField();
        pipeInsulationCheckBox = new javax.swing.JCheckBox();
        addButton = new javax.swing.JButton();
        discardButton = new javax.swing.JButton();
        pipeSizeLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        pipeSizeDiameterLabel = new javax.swing.JLabel();
        pipeColoursComboBox = new javax.swing.JComboBox();
        pipeGradeComboBox = new javax.swing.JComboBox();
        pipeGradeLabel = new javax.swing.JLabel();
        pipeSizeLengthTextField = new javax.swing.JTextField();
        pipeSizeLengthLabel = new javax.swing.JLabel();
        pipeColoursLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pipeQuantityLabel.setText("Quantity:");

        pipeReinforcementCheckBox.setText("Reinforcement");
        pipeReinforcementCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pipeReinforcementCheckBoxActionPerformed(evt);
            }
        });

        pipeChemResCheckBox.setText("Chemical Resistance");
        pipeChemResCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pipeChemResCheckBoxActionPerformed(evt);
            }
        });

        pipeSizeDiameterTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pipeSizeDiameterTextField.setText("1inches");
        pipeSizeDiameterTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pipeSizeDiameterTextFieldActionPerformed(evt);
            }
        });

        pipeInsulationCheckBox.setText("Insulation");
        pipeInsulationCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pipeInsulationCheckBoxActionPerformed(evt);
            }
        });

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        discardButton.setText("Discard");

        pipeSizeLabel.setText("Size:");

        titleLabel.setFont(new java.awt.Font("Serif", 2, 14));
        titleLabel.setText("Pipes 'R' Us");
        titleLabel.setToolTipText("For all your pipe needs!");

        pipeSizeDiameterLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        pipeSizeDiameterLabel.setText("Diameter:");

        pipeColoursComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2" }));

        pipeGradeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        pipeGradeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pipeGradeComboBoxActionPerformed(evt);
            }
        });

        pipeGradeLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        pipeGradeLabel.setText("Grade:");

        pipeSizeLengthTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pipeSizeLengthTextField.setText("1m");
        pipeSizeLengthTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pipeSizeLengthTextFieldActionPerformed(evt);
            }
        });

        pipeSizeLengthLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        pipeSizeLengthLabel.setText("Length:");

        pipeColoursLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        pipeColoursLabel.setText("Colours:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pipeSizeLabel)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(pipeSizeLengthLabel)
                                        .addComponent(pipeSizeDiameterLabel))
                                    .addGap(29, 29, 29)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(pipeSizeLengthTextField)
                                        .addComponent(pipeSizeDiameterTextField)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(pipeColoursLabel)
                                        .addComponent(pipeGradeLabel))
                                    .addGap(41, 41, 41)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(pipeGradeComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pipeColoursComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(20, 20, 20)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pipeReinforcementCheckBox)
                                .addComponent(pipeChemResCheckBox)
                                .addComponent(pipeInsulationCheckBox)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(addButton)
                                        .addComponent(pipeQuantityLabel))
                                    .addGap(26, 26, 26)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(discardButton)
                                        .addComponent(pipeQuantitySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addComponent(titleLabel))
                    .addContainerGap(29, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(titleLabel)
                            .addGap(38, 38, 38)
                            .addComponent(pipeSizeLabel)
                            .addGap(12, 12, 12)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(pipeSizeLengthLabel)
                                .addComponent(pipeSizeLengthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(pipeSizeDiameterLabel)
                                .addComponent(pipeSizeDiameterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(pipeGradeLabel)
                                .addComponent(pipeGradeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(pipeColoursLabel)
                                .addComponent(pipeColoursComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(addButton)
                                .addComponent(discardButton)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(7, 7, 7)
                            .addComponent(pipeInsulationCheckBox)
                            .addGap(4, 4, 4)
                            .addComponent(pipeReinforcementCheckBox)
                            .addGap(31, 31, 31)
                            .addComponent(pipeChemResCheckBox)
                            .addGap(37, 37, 37)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(pipeQuantityLabel)
                                .addComponent(pipeQuantitySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(25, 25, 25)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void pipeReinforcementCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pipeReinforcementCheckBoxActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_pipeReinforcementCheckBoxActionPerformed

private void pipeChemResCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pipeChemResCheckBoxActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_pipeChemResCheckBoxActionPerformed

private void pipeSizeDiameterTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pipeSizeDiameterTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_pipeSizeDiameterTextFieldActionPerformed

private void pipeInsulationCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pipeInsulationCheckBoxActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_pipeInsulationCheckBoxActionPerformed

private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
  // 
}//GEN-LAST:event_addButtonActionPerformed

private void pipeGradeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pipeGradeComboBoxActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_pipeGradeComboBoxActionPerformed

private void pipeSizeLengthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pipeSizeLengthTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_pipeSizeLengthTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(popUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(popUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(popUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(popUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new popUp().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton discardButton;
    private javax.swing.JCheckBox pipeChemResCheckBox;
    private javax.swing.JComboBox pipeColoursComboBox;
    private javax.swing.JLabel pipeColoursLabel;
    private javax.swing.JComboBox pipeGradeComboBox;
    private javax.swing.JLabel pipeGradeLabel;
    private javax.swing.JCheckBox pipeInsulationCheckBox;
    private javax.swing.JLabel pipeQuantityLabel;
    private javax.swing.JSpinner pipeQuantitySpinner;
    private javax.swing.JCheckBox pipeReinforcementCheckBox;
    private javax.swing.JLabel pipeSizeDiameterLabel;
    private javax.swing.JTextField pipeSizeDiameterTextField;
    private javax.swing.JLabel pipeSizeLabel;
    private javax.swing.JLabel pipeSizeLengthLabel;
    private javax.swing.JTextField pipeSizeLengthTextField;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
