INSERT INTO WorldCupSystem.Team (Team_ID, Team_Name, Team_Qualified) VALUES ('0', 'Albania', '0');
INSERT INTO WorldCupSystem.Team (Team_ID, Team_Name, Team_Qualified) VALUES ('1', 'Andorra', '0');
INSERT INTO WorldCupSystem.Team (Team_ID, Team_Name, Team_Qualified) VALUES ('2', 'Armenia', '0');
INSERT INTO WorldCupSystem.Team (Team_ID, Team_Name, Team_Qualified) VALUES ('3', 'Austria', '0');
INSERT INTO WorldCupSystem.Team (Team_ID, Team_Name, Team_Qualified) VALUES ('4', 'Azerbaijan', '0');
INSERT INTO WorldCupSystem.Team (Team_ID, Team_Name, Team_Qualified) VALUES ('5', 'Belarus', '0');
INSERT INTO WorldCupSystem.Team (Team_ID, Team_Name, Team_Qualified) VALUES ('6', 'Belgium', '0');
INSERT INTO WorldCupSystem.Team (Team_ID, Team_Name, Team_Qualified) VALUES ('7', 'Bosnia-Herzegovina', '0');
INSERT INTO WorldCupSystem.Team (Team_ID, Team_Name, Team_Qualified) VALUES ('8', 'Bulgaria', '0');
INSERT INTO WorldCupSystem.Team (Team_ID, Team_Name, Team_Qualified) VALUES ('9', 'Croatia', '0');
INSERT INTO WorldCupSystem.Team (Team_ID, Team_Name, Team_Qualified) VALUES ('10', 'Cyprus', '0');
INSERT INTO WorldCupSystem.Team (Team_ID, Team_Name, Team_Qualified) VALUES ('11', 'Czech Republic', '0');
INSERT INTO WorldCupSystem.Team (Team_ID, Team_Name, Team_Qualified) VALUES ('12', 'Denmark', '0');
INSERT INTO WorldCupSystem.Team (Team_ID, Team_Name, Team_Qualified) VALUES ('13', 'England', '0');
INSERT INTO WorldCupSystem.Team (Team_ID, Team_Name, Team_Qualified) VALUES ('14', 'Estonia', '0');
INSERT INTO WorldCupSystem.Team (Team_ID, Team_Name, Team_Qualified) VALUES ('15', 'Faroe Islands', '0');
INSERT INTO WorldCupSystem.Team (Team_ID, Team_Name, Team_Qualified) VALUES ('16', 'Finland', '0');
INSERT INTO WorldCupSystem.Team (Team_ID, Team_Name, Team_Qualified) VALUES ('17', 'France', '0');
INSERT INTO WorldCupSystem.Team (Team_ID, Team_Name, Team_Qualified) VALUES ('18', 'FYR Macedonia', '0');
INSERT INTO WorldCupSystem.Team (Team_ID, Team_Name, Team_Qualified) VALUES ('19', 'Georgia', '0');
INSERT INTO WorldCupSystem.Team (Team_ID, Team_Name, Team_Qualified) VALUES ('20', 'Germany', '0');
INSERT INTO WorldCupSystem.Team (Team_ID, Team_Name, Team_Qualified) VALUES ('21', 'Greece', '0');
INSERT INTO WorldCupSystem.Team (Team_ID, Team_Name, Team_Qualified) VALUES ('22', 'Hungary', '0');
INSERT INTO WorldCupSystem.Team (Team_ID, Team_Name, Team_Qualified) VALUES ('23', 'Iceland', '0');
INSERT INTO WorldCupSystem.Team (Team_ID, Team_Name, Team_Qualified) VALUES ('24', 'Israel', '0');
INSERT INTO WorldCupSystem.Team (Team_ID, Team_Name, Team_Qualified) VALUES ('25', 'Italy', '0');
INSERT INTO WorldCupSystem.Team (Team_ID, Team_Name, Team_Qualified) VALUES ('26', 'Kazakhstan', '0');
INSERT INTO WorldCupSystem.Team (Team_ID, Team_Name, Team_Qualified) VALUES ('27', 'Latvia', '0');
INSERT INTO WorldCupSystem.Team (Team_ID, Team_Name, Team_Qualified) VALUES ('28', 'Liechtenstein', '0');
INSERT INTO WorldCupSystem.Team (Team_ID, Team_Name, Team_Qualified) VALUES ('29', 'Lithuania', '0');
INSERT INTO WorldCupSystem.Team (Team_ID, Team_Name, Team_Qualified) VALUES ('30', 'Luxembourg', '0');
INSERT INTO WorldCupSystem.Team (Team_ID, Team_Name, Team_Qualified) VALUES ('31', 'Malta', '0');
INSERT INTO WorldCupSystem.Team (Team_ID, Team_Name, Team_Qualified) VALUES ('32', 'Moldova', '0');
INSERT INTO WorldCupSystem.Team (Team_ID, Team_Name, Team_Qualified) VALUES ('33', 'Montenegro', '0');
INSERT INTO WorldCupSystem.Team (Team_ID, Team_Name, Team_Qualified) VALUES ('34', 'Netherlands', '0');
INSERT INTO WorldCupSystem.Team (Team_ID, Team_Name, Team_Qualified) VALUES ('35', 'Northern Ireland', '0');
INSERT INTO WorldCupSystem.Team (Team_ID, Team_Name, Team_Qualified) VALUES ('36', 'Norway', '0');
INSERT INTO WorldCupSystem.Team (Team_ID, Team_Name, Team_Qualified) VALUES ('37', 'Poland', '0');
INSERT INTO WorldCupSystem.Team (Team_ID, Team_Name, Team_Qualified) VALUES ('38', 'Portugal', '0');
INSERT INTO WorldCupSystem.Team (Team_ID, Team_Name, Team_Qualified) VALUES ('39', 'Republic of Ireland', '0');
INSERT INTO WorldCupSystem.Team (Team_ID, Team_Name, Team_Qualified) VALUES ('40', 'Romania', '0');
INSERT INTO WorldCupSystem.Team (Team_ID, Team_Name, Team_Qualified) VALUES ('41', 'Russi', '0');