-- MySQL Script generated by MySQL Workbench
-- Thu 10 Dec 2015 01:23:27 GMT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dwm1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dwm1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dwm1` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `dwm1` ;

-- -----------------------------------------------------
-- Table `dwm1`.`Vehicle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dwm1`.`Vehicle` ;

CREATE TABLE IF NOT EXISTS `dwm1`.`Vehicle` (
  `VehicleID` VARCHAR(12) NOT NULL,
  `VehicleMake` VARCHAR(45) NULL,
  `VehicleColour` VARCHAR(45) NULL,
  `VehicleEngineSize` VARCHAR(45) NULL,
  `VehicleFuelType` VARCHAR(45) NULL,
  `VehicleTypeApproval` VARCHAR(45) NULL,
  `VehicleYearOfManufacture` INT NULL,
  `VehicleDateRegistered` DATETIME NULL,
  `VehicleTaxExpires` DATETIME NULL,
  `VehicleMoTExpires` DATETIME NULL,
  PRIMARY KEY (`VehicleID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwm1`.`TimeYear`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dwm1`.`TimeYear` ;

CREATE TABLE IF NOT EXISTS `dwm1`.`TimeYear` (
  `TimeYearID` INT NOT NULL,
  `TimeYear` INT NULL,
  PRIMARY KEY (`TimeYearID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwm1`.`TimeMonth`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dwm1`.`TimeMonth` ;

CREATE TABLE IF NOT EXISTS `dwm1`.`TimeMonth` (
  `TimeMonthID` INT NOT NULL,
  `TimeMonth` INT NULL,
  `TimeMonthName` VARCHAR(45) NULL,
  `TimeYearID` INT NOT NULL,
  PRIMARY KEY (`TimeMonthID`),
  INDEX `fk_TimeMonth_TimeYear1_idx` (`TimeYearID` ASC),
  CONSTRAINT `fk_TimeMonth_TimeYear1`
    FOREIGN KEY (`TimeYearID`)
    REFERENCES `dwm1`.`TimeYear` (`TimeYearID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwm1`.`TimeDay`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dwm1`.`TimeDay` ;

CREATE TABLE IF NOT EXISTS `dwm1`.`TimeDay` (
  `TimeDayID` INT NOT NULL,
  `TimeDay` INT NULL,
  `TimeMonthID` INT NOT NULL,
  PRIMARY KEY (`TimeDayID`),
  INDEX `fk_TimeDay_TimeMonth1_idx` (`TimeMonthID` ASC),
  CONSTRAINT `fk_TimeDay_TimeMonth1`
    FOREIGN KEY (`TimeMonthID`)
    REFERENCES `dwm1`.`TimeMonth` (`TimeMonthID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwm1`.`Time`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dwm1`.`Time` ;

CREATE TABLE IF NOT EXISTS `dwm1`.`Time` (
  `TimeID` INT NOT NULL,
  `TimeClockTime` TIME NULL,
  `TimeDayID` INT NOT NULL,
  PRIMARY KEY (`TimeID`),
  INDEX `fk_Time_TimeDay1_idx` (`TimeDayID` ASC),
  CONSTRAINT `fk_Time_TimeDay1`
    FOREIGN KEY (`TimeDayID`)
    REFERENCES `dwm1`.`TimeDay` (`TimeDayID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwm1`.`Owner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dwm1`.`Owner` ;

CREATE TABLE IF NOT EXISTS `dwm1`.`Owner` (
  `OwnerID` INT NOT NULL,
  `OwnerName` VARCHAR(255) NULL,
  `OwnerEmail` VARCHAR(45) NULL DEFAULT '',
  `OwnerPhone` VARCHAR(45) NULL,
  PRIMARY KEY (`OwnerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwm1`.`LocalAuthority`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dwm1`.`LocalAuthority` ;

CREATE TABLE IF NOT EXISTS `dwm1`.`LocalAuthority` (
  `LocalAuthorityID` INT NOT NULL,
  `LocalAuthorityName` VARCHAR(45) NULL,
  `LocalAuthorityAddress` VARCHAR(45) NULL,
  `LocalAuthorityPhone` VARCHAR(45) NULL,
  PRIMARY KEY (`LocalAuthorityID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwm1`.`Station`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dwm1`.`Station` ;

CREATE TABLE IF NOT EXISTS `dwm1`.`Station` (
  `StationID` INT NOT NULL,
  `StationAddress` VARCHAR(45) NULL,
  `StationPhone` VARCHAR(45) NULL,
  `StationPoliceChief` VARCHAR(45) NULL,
  PRIMARY KEY (`StationID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwm1`.`LocationRegion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dwm1`.`LocationRegion` ;

CREATE TABLE IF NOT EXISTS `dwm1`.`LocationRegion` (
  `LocationRegionID` INT NOT NULL,
  `LocationRegionName` VARCHAR(45) NULL,
  PRIMARY KEY (`LocationRegionID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwm1`.`LocationCity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dwm1`.`LocationCity` ;

CREATE TABLE IF NOT EXISTS `dwm1`.`LocationCity` (
  `LocationCityID` INT NOT NULL,
  `LocationCityName` VARCHAR(255) NULL,
  `LocationRegionID` INT NOT NULL,
  PRIMARY KEY (`LocationCityID`),
  INDEX `fk_StationCIty_Region1_idx` (`LocationRegionID` ASC),
  CONSTRAINT `fk_LocationCity_LocationRegion`
    FOREIGN KEY (`LocationRegionID`)
    REFERENCES `dwm1`.`LocationRegion` (`LocationRegionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwm1`.`Location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dwm1`.`Location` ;

CREATE TABLE IF NOT EXISTS `dwm1`.`Location` (
  `LocationID` INT NOT NULL,
  `LocationAddress` VARCHAR(45) NULL,
  `LocationCityID` INT NOT NULL,
  PRIMARY KEY (`LocationID`),
  INDEX `fk_LocationID_StationCIty1_idx` (`LocationCityID` ASC),
  CONSTRAINT `fk_Location_LocationCity`
    FOREIGN KEY (`LocationCityID`)
    REFERENCES `dwm1`.`LocationCity` (`LocationCityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwm1`.`Suspect`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dwm1`.`Suspect` ;

CREATE TABLE IF NOT EXISTS `dwm1`.`Suspect` (
  `SuspectID` INT NOT NULL,
  `SuspectName` VARCHAR(45) NULL,
  PRIMARY KEY (`SuspectID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwm1`.`CarTheft`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dwm1`.`CarTheft` ;

CREATE TABLE IF NOT EXISTS `dwm1`.`CarTheft` (
  `CarTheftID` INT NOT NULL,
  `StationID` INT NOT NULL,
  `LocalAuthorityID` INT NOT NULL,
  `LocationID` INT NOT NULL,
  `OwnerID` INT NOT NULL,
  `TimeID` INT NOT NULL,
  `VehicleID` VARCHAR(12) NOT NULL,
  `SuspectID` INT NOT NULL,
  PRIMARY KEY (`CarTheftID`),
  INDEX `fk_CarTheft_Station1_idx` (`StationID` ASC),
  INDEX `fk_CarTheft_LocalAuthority1_idx` (`LocalAuthorityID` ASC),
  INDEX `fk_CarTheft_LocationID1_idx` (`LocationID` ASC),
  INDEX `fk_CarTheft_Owner1_idx` (`OwnerID` ASC),
  INDEX `fk_CarTheft_Time1_idx` (`TimeID` ASC),
  INDEX `fk_CarTheft_Vehicle1_idx` (`VehicleID` ASC),
  INDEX `fk_CarTheft_Suspect1_idx` (`SuspectID` ASC),
  CONSTRAINT `fk_CarTheft_Station1`
    FOREIGN KEY (`StationID`)
    REFERENCES `dwm1`.`Station` (`StationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CarTheft_LocalAuthority1`
    FOREIGN KEY (`LocalAuthorityID`)
    REFERENCES `dwm1`.`LocalAuthority` (`LocalAuthorityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CarTheft_LocationID1`
    FOREIGN KEY (`LocationID`)
    REFERENCES `dwm1`.`Location` (`LocationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CarTheft_Owner1`
    FOREIGN KEY (`OwnerID`)
    REFERENCES `dwm1`.`Owner` (`OwnerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CarTheft_Time1`
    FOREIGN KEY (`TimeID`)
    REFERENCES `dwm1`.`Time` (`TimeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CarTheft_Vehicle1`
    FOREIGN KEY (`VehicleID`)
    REFERENCES `dwm1`.`Vehicle` (`VehicleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CarTheft_Suspect1`
    FOREIGN KEY (`SuspectID`)
    REFERENCES `dwm1`.`Suspect` (`SuspectID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwm1`.`SeizureNotice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dwm1`.`SeizureNotice` ;

CREATE TABLE IF NOT EXISTS `dwm1`.`SeizureNotice` (
  `SeizureNoticeID` INT NOT NULL,
  `TimeID` INT NOT NULL,
  `LocalAuthorityID` INT NOT NULL,
  `StationID` INT NOT NULL,
  `LocationID` INT NOT NULL,
  `VehicleID` VARCHAR(12) NOT NULL,
  `OwnerID` INT NOT NULL,
  PRIMARY KEY (`SeizureNoticeID`),
  INDEX `fk_SeizureNotice_Time1_idx` (`TimeID` ASC),
  INDEX `fk_SeizureNotice_Vehicle1_idx` (`VehicleID` ASC),
  INDEX `fk_SeizureNotice_LocalAuthority1_idx` (`LocalAuthorityID` ASC),
  INDEX `fk_SeizureNotice_Owner1_idx` (`OwnerID` ASC),
  INDEX `fk_SeizureNotice_Station1_idx` (`StationID` ASC),
  INDEX `fk_SeizureNotice_LocationID1_idx` (`LocationID` ASC),
  CONSTRAINT `fk_SeizureNotice_Time1`
    FOREIGN KEY (`TimeID`)
    REFERENCES `dwm1`.`Time` (`TimeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SeizureNotice_Vehicle1`
    FOREIGN KEY (`VehicleID`)
    REFERENCES `dwm1`.`Vehicle` (`VehicleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SeizureNotice_LocalAuthority1`
    FOREIGN KEY (`LocalAuthorityID`)
    REFERENCES `dwm1`.`LocalAuthority` (`LocalAuthorityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SeizureNotice_Owner1`
    FOREIGN KEY (`OwnerID`)
    REFERENCES `dwm1`.`Owner` (`OwnerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SeizureNotice_Station1`
    FOREIGN KEY (`StationID`)
    REFERENCES `dwm1`.`Station` (`StationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SeizureNotice_LocationID1`
    FOREIGN KEY (`LocationID`)
    REFERENCES `dwm1`.`Location` (`LocationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
