-- MySQL Script generated by MySQL Workbench
-- Tue 08 Dec 2015 20:04:13 GMT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Vehicle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Vehicle` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Vehicle` (
  `VehicleID` VARCHAR(12) NOT NULL,
  `VehicleMake` VARCHAR(45) NULL,
  `VehicleColour` VARCHAR(45) NULL,
  `VehicleEngineSize` VARCHAR(45) NULL,
  `VehicleFuelType` VARCHAR(45) NULL,
  `VehicleStatus` VARCHAR(45) NULL,
  `VehicleTypeApproval` VARCHAR(45) NULL,
  `VehicleYearOfManufacture` DATETIME NULL,
  `VehicleDateRegistered` DATETIME NULL,
  `VehicleTaxExpires` DATETIME NULL,
  `VehicleMoTExpires` DATETIME NULL,
  PRIMARY KEY (`VehicleID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Time`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Time` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Time` (
  `TimeID` INT NOT NULL,
  `TimeWeek` DATETIME NULL,
  `TimeDay` DATETIME NULL,
  `TimeClockTime` DATETIME NULL,
  PRIMARY KEY (`TimeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Owner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Owner` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Owner` (
  `OwnerID` INT NOT NULL,
  `OwnerCompany` TINYINT(1) NULL,
  `OwnerDetails` VARCHAR(45) NULL,
  PRIMARY KEY (`OwnerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LocalAuthority`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`LocalAuthority` ;

CREATE TABLE IF NOT EXISTS `mydb`.`LocalAuthority` (
  `LocalAuthorityID` INT NOT NULL,
  `LocalAuthorityName` VARCHAR(45) NULL,
  `LocalAuthorityPhone` VARCHAR(45) NULL,
  PRIMARY KEY (`LocalAuthorityID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Station`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Station` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Station` (
  `StationID` INT NOT NULL,
  `StationDescription` VARCHAR(255) NULL,
  `StationPoliceChief` VARCHAR(45) NULL,
  PRIMARY KEY (`StationID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LocationRegion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`LocationRegion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`LocationRegion` (
  `LocationRegionID` INT NOT NULL,
  `LocationRegionName` VARCHAR(45) NULL,
  PRIMARY KEY (`LocationRegionID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LocationCIty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`LocationCIty` ;

CREATE TABLE IF NOT EXISTS `mydb`.`LocationCIty` (
  `LocationCityID` INT NOT NULL,
  `LocationCityName` VARCHAR(255) NULL,
  `LocationRegionID` INT NOT NULL,
  PRIMARY KEY (`LocationCityID`),
  INDEX `fk_StationCIty_Region1_idx` (`LocationRegionID` ASC),
  CONSTRAINT `fk_StationCIty_Region1`
    FOREIGN KEY (`LocationRegionID`)
    REFERENCES `mydb`.`LocationRegion` (`LocationRegionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LocationID`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`LocationID` ;

CREATE TABLE IF NOT EXISTS `mydb`.`LocationID` (
  `LocationID` INT NOT NULL,
  `LocationCityID` INT NOT NULL,
  `LocationAddress` VARCHAR(45) NULL,
  PRIMARY KEY (`LocationID`),
  INDEX `fk_LocationID_StationCIty1_idx` (`LocationCityID` ASC),
  CONSTRAINT `fk_LocationID_StationCIty1`
    FOREIGN KEY (`LocationCityID`)
    REFERENCES `mydb`.`LocationCIty` (`LocationCityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Suspect`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Suspect` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Suspect` (
  `SuspectID` INT NOT NULL,
  `SuspectName` VARCHAR(45) NULL,
  PRIMARY KEY (`SuspectID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CarTheft`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CarTheft` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CarTheft` (
  `CarTheftID` INT NOT NULL,
  `StationID` INT NOT NULL,
  `LocalAuthorityID` INT NOT NULL,
  `LocationID` INT NOT NULL,
  `OwnerID` INT NOT NULL,
  `TimeID` INT NOT NULL,
  `VehicleID` VARCHAR(12) NOT NULL,
  `Suspect_SuspectID` INT NOT NULL,
  PRIMARY KEY (`CarTheftID`),
  INDEX `fk_CarTheft_Station1_idx` (`StationID` ASC),
  INDEX `fk_CarTheft_LocalAuthority1_idx` (`LocalAuthorityID` ASC),
  INDEX `fk_CarTheft_LocationID1_idx` (`LocationID` ASC),
  INDEX `fk_CarTheft_Owner1_idx` (`OwnerID` ASC),
  INDEX `fk_CarTheft_Time1_idx` (`TimeID` ASC),
  INDEX `fk_CarTheft_Vehicle1_idx` (`VehicleID` ASC),
  INDEX `fk_CarTheft_Suspect1_idx` (`Suspect_SuspectID` ASC),
  CONSTRAINT `fk_CarTheft_Station1`
    FOREIGN KEY (`StationID`)
    REFERENCES `mydb`.`Station` (`StationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CarTheft_LocalAuthority1`
    FOREIGN KEY (`LocalAuthorityID`)
    REFERENCES `mydb`.`LocalAuthority` (`LocalAuthorityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CarTheft_LocationID1`
    FOREIGN KEY (`LocationID`)
    REFERENCES `mydb`.`LocationID` (`LocationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CarTheft_Owner1`
    FOREIGN KEY (`OwnerID`)
    REFERENCES `mydb`.`Owner` (`OwnerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CarTheft_Time1`
    FOREIGN KEY (`TimeID`)
    REFERENCES `mydb`.`Time` (`TimeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CarTheft_Vehicle1`
    FOREIGN KEY (`VehicleID`)
    REFERENCES `mydb`.`Vehicle` (`VehicleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CarTheft_Suspect1`
    FOREIGN KEY (`Suspect_SuspectID`)
    REFERENCES `mydb`.`Suspect` (`SuspectID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SeizureNotice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`SeizureNotice` ;

CREATE TABLE IF NOT EXISTS `mydb`.`SeizureNotice` (
  `SeizureNoticeID` INT NOT NULL,
  `TimeID` INT NOT NULL,
  `VehicleID` VARCHAR(12) NOT NULL,
  `LocalAuthorityID` INT NOT NULL,
  `OwnerID` INT NOT NULL,
  `StationID` INT NOT NULL,
  `LocationID` INT NOT NULL,
  PRIMARY KEY (`SeizureNoticeID`),
  INDEX `fk_SeizureNotice_Time1_idx` (`TimeID` ASC),
  INDEX `fk_SeizureNotice_Vehicle1_idx` (`VehicleID` ASC),
  INDEX `fk_SeizureNotice_LocalAuthority1_idx` (`LocalAuthorityID` ASC),
  INDEX `fk_SeizureNotice_Owner1_idx` (`OwnerID` ASC),
  INDEX `fk_SeizureNotice_Station1_idx` (`StationID` ASC),
  INDEX `fk_SeizureNotice_LocationID1_idx` (`LocationID` ASC),
  CONSTRAINT `fk_SeizureNotice_Time1`
    FOREIGN KEY (`TimeID`)
    REFERENCES `mydb`.`Time` (`TimeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SeizureNotice_Vehicle1`
    FOREIGN KEY (`VehicleID`)
    REFERENCES `mydb`.`Vehicle` (`VehicleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SeizureNotice_LocalAuthority1`
    FOREIGN KEY (`LocalAuthorityID`)
    REFERENCES `mydb`.`LocalAuthority` (`LocalAuthorityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SeizureNotice_Owner1`
    FOREIGN KEY (`OwnerID`)
    REFERENCES `mydb`.`Owner` (`OwnerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SeizureNotice_Station1`
    FOREIGN KEY (`StationID`)
    REFERENCES `mydb`.`Station` (`StationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SeizureNotice_LocationID1`
    FOREIGN KEY (`LocationID`)
    REFERENCES `mydb`.`LocationID` (`LocationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
