INSERT INTO WorldCupSystem.Team VALUES ('0', 'Albania', '0');
INSERT INTO WorldCupSystem.Team VALUES ('1', 'Andorra', '0');
INSERT INTO WorldCupSystem.Team VALUES ('2', 'Armenia', '0');
INSERT INTO WorldCupSystem.Team VALUES ('3', 'Austria', '0');
INSERT INTO WorldCupSystem.Team VALUES ('4', 'Azerbaijan', '0');
INSERT INTO WorldCupSystem.Team VALUES ('5', 'Belarus', '0');
INSERT INTO WorldCupSystem.Team VALUES ('6', 'Belgium', '0');
INSERT INTO WorldCupSystem.Team VALUES ('7', 'Bosnia-Herzegovina', '0');
INSERT INTO WorldCupSystem.Team VALUES ('8', 'Bulgaria', '0');
INSERT INTO WorldCupSystem.Team VALUES ('9', 'Croatia', '0');
INSERT INTO WorldCupSystem.Team VALUES ('10', 'Cyprus', '0');
INSERT INTO WorldCupSystem.Team VALUES ('11', 'Czech Republic', '0');
INSERT INTO WorldCupSystem.Team VALUES ('12', 'Denmark', '0');
INSERT INTO WorldCupSystem.Team VALUES ('13', 'England', '0');
INSERT INTO WorldCupSystem.Team VALUES ('14', 'Estonia', '0');
INSERT INTO WorldCupSystem.Team VALUES ('15', 'Faroe Islands', '0');
INSERT INTO WorldCupSystem.Team VALUES ('16', 'Finland', '0');
INSERT INTO WorldCupSystem.Team VALUES ('17', 'France', '0');
INSERT INTO WorldCupSystem.Team VALUES ('18', 'FYR Macedonia', '0');
INSERT INTO WorldCupSystem.Team VALUES ('19', 'Georgia', '0');
INSERT INTO WorldCupSystem.Team VALUES ('20', 'Germany', '0');
INSERT INTO WorldCupSystem.Team VALUES ('21', 'Greece', '0');
INSERT INTO WorldCupSystem.Team VALUES ('22', 'Hungary', '0');
INSERT INTO WorldCupSystem.Team VALUES ('23', 'Iceland', '0');
INSERT INTO WorldCupSystem.Team VALUES ('24', 'Israel', '0');
INSERT INTO WorldCupSystem.Team VALUES ('25', 'Italy', '0');
INSERT INTO WorldCupSystem.Team VALUES ('26', 'Kazakhstan', '0');
INSERT INTO WorldCupSystem.Team VALUES ('27', 'Latvia', '0');
INSERT INTO WorldCupSystem.Team VALUES ('28', 'Liechtenstein', '0');
INSERT INTO WorldCupSystem.Team VALUES ('29', 'Lithuania', '0');
INSERT INTO WorldCupSystem.Team VALUES ('30', 'Luxembourg', '0');
INSERT INTO WorldCupSystem.Team VALUES ('31', 'Malta', '0');
INSERT INTO WorldCupSystem.Team VALUES ('32', 'Moldova', '0');
INSERT INTO WorldCupSystem.Team VALUES ('33', 'Montenegro', '0');
INSERT INTO WorldCupSystem.Team VALUES ('34', 'Netherlands', '0');
INSERT INTO WorldCupSystem.Team VALUES ('35', 'Northern Ireland', '0');
INSERT INTO WorldCupSystem.Team VALUES ('36', 'Norway', '0');
INSERT INTO WorldCupSystem.Team VALUES ('37', 'Poland', '0');
INSERT INTO WorldCupSystem.Team VALUES ('38', 'Portugal', '0');
INSERT INTO WorldCupSystem.Team VALUES ('39', 'Republic of Ireland', '0');
INSERT INTO WorldCupSystem.Team VALUES ('40', 'Romania', '0');
INSERT INTO WorldCupSystem.Team VALUES ('41', 'Russia', '0');
INSERT INTO WorldCupSystem.Team VALUES ('42', 'San Marino', '0');
INSERT INTO WorldCupSystem.Team VALUES ('43', 'Scotland', '0');
INSERT INTO WorldCupSystem.Team VALUES ('44', 'Serbia', '0');
INSERT INTO WorldCupSystem.Team VALUES ('45', 'Slovakia', '0');
INSERT INTO WorldCupSystem.Team VALUES ('46', 'Slovenia', '0');
INSERT INTO WorldCupSystem.Team VALUES ('47', 'Spain', '0');
INSERT INTO WorldCupSystem.Team VALUES ('48', 'Sweden	', '0');
INSERT INTO WorldCupSystem.Team VALUES ('49', 'Switzerland', '0');
INSERT INTO WorldCupSystem.Team VALUES ('50', 'Turkey', '0');
INSERT INTO WorldCupSystem.Team VALUES ('51', 'Ukraine', '0');
INSERT INTO WorldCupSystem.Team VALUES ('52', 'Wales', '0');